#!/bin/bash

while [ $# -gt 0 ]; do
  case "$1" in
    --start=*)
      start="${1#*=}"
      ;;
    --end=*)
      end="${1#*=}"
      ;;
    --transportation-method=*)
      transportation="${1#*=}"
      ;;
    *)
      printf "***************************\n"
      printf "* Error: Invalid argument.*\n"
      printf "***************************\n"
      exit 1
  esac
  shift
done

if [[ -z $start || -z $end || -z $transportation ]];
then
    echo `date`" - Missing mandatory arguments: start, end and  transportation. "
    echo `date`" - Usage: --start [startCityName] --end [EndCityName] --transportation-method [methid-name] . "
    exit 1
fi




printf "Argument start is %s\n" "$start"
printf "Argument end is %s\n" "$end"
printf "Argument transportation-method is %s\n" "$transportation"

result=$(curl -X GET --header "Accept: */*" "http://localhost:8080/emission/v1/calculate/start/$start/end/$end/transportMethod/$transportation")
echo "Response from server"
echo $result
exit
